### ISSUE TITLE
Update example to use CircleCI 2.0?

### ISSUE THREAD

**Issue by woolfel** [circleci/circle-cloudformation#2]
I have a few projects using circleCI with AWS. It would be nice if this example is updated to use circleCI 2.0 configuration instead of 1.0.

**Comment by FelicianoTech** [comment]
Hi. This project has been unmaintained for 3 years so I'm going to archive it. If we do end up having a CircleCI 2.0 example for this, you'll likely see it surface on CircleCI Discuss, the blog, or Docs.
